### ISSUE TITLE
训练好的model

### ISSUE THREAD

**Issue by a75732410** [luo3300612/image-captioning-DLCT#15]
您好，请问能提供一下训练好的model吗？

**Comment by luo3300612** [comment]
这里有训练好的模型[pretrained_model.pth](https://pan.baidu.com/s/1xVZO7t8k4H_l3aEyuA-KXQ). Acess code: jcj6.
评估指标为
{'BLEU': [0.8136727001615207, 0.6606095421082421, 0.5167535314080227, 0.39790755018790197], 'METEOR': 0.29522868252436046, 'ROUGE': 0.5914367650104326, 'CIDEr': 1.3382047139781112, 'SPICE': 0.22953477359195887}

**Comment by a75732410** [comment]
谢谢大佬~~~


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "luo3300612/image-captioning-DLCT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月9日(星期二) 下午3:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [luo3300612/image-captioning-DLCT] 训练好的model (#15)





 
这里有训练好的模型pretrained_model.pth. Acess code: jcj6.
 评估指标为
 {'BLEU': [0.8136727001615207, 0.6606095421082421, 0.5167535314080227, 0.39790755018790197], 'METEOR': 0.29522868252436046, 'ROUGE': 0.5914367650104326, 'CIDEr': 1.3382047139781112, 'SPICE': 0.22953477359195887}
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
