### ISSUE TITLE
how are alignment graph obtained for new datasets

### ISSUE THREAD

**Issue by hyhwdq** [luo3300612/image-captioning-DLCT#19]
Hi, in your coding,h5py.File features has keys like ['%d_features' % image_id] , ['%d_grids' % image_id], ['%d_boxes' % image_id], ['%d_size' % image_id], ['%d_mask' % image_id], If I have a new data set, can I just use align.py to get geometric alignment graph after I get grid features and region features using extract_region_feature.py and grid-feats-vqa.

**Comment by luo3300612** [comment]
Yes, all codes for generating geometric alignment graph are in align.ipynb with visualization function.
