### ISSUE TITLE
关于pth大小

### ISSUE THREAD

**Issue by haijie945** [luo3300612/image-captioning-DLCT#26]
请问跑完的模型是200M+嘛？我下载了您提供的pretrained_model.pth，240MB，为什么我跑出来有700M+。
![size](https://user-images.githubusercontent.com/69234726/144747738-64f09607-fa87-40bd-9ce9-0c827e5fb465.jpg)

**Comment by luo3300612** [comment]
你好，这个是因为跑代码的时候除了保存模型还保存了优化器Adam的参数以便中断的时候继续训练，而我给的文件里只有模型本身的
