### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'train_on_pred_boxes'

### ISSUE THREAD

**Issue by hwbhwbgao** [luo3300612/image-captioning-DLCT#30]
[/usr/local/lib/python3.7/dist-packages/detectron2/config/config.py](https://localhost:8080/#) in wrapped(self, *args, **kwargs)
    188             if _called_with_cfg(*args, **kwargs):
    189                 explicit_args = _get_args_from_config(from_config_func, *args, **kwargs)
--> 190                 init_func(self, **explicit_args)
    191             else:
    192                 init_func(self, *args, **kwargs)

TypeError: __init__() got an unexpected keyword argument 'train_on_pred_boxes'
作者您好，我在复现您论文时，在实现提取特征的代码时出现该问题，我查询了相关的，但是没有解决？

**Comment by competent-s** [comment]
我也遇到了同样的问题，请问您解决了吗？

**Comment by hwbhwbgao** [comment]
> 

我是在colab上运行该代码的，具体特征提取已经完成。但是对于该问题解决方案：
!pip install -U git+https://github.com/facebookresearch/fvcore
!python -m pip install 'git+https://github.com/facebookresearch/detectron2.git@ffff8ac'
希望对您有帮助！

**Comment by competent-s** [comment]
> > 
> 
> 我是在colab上运行该代码的，具体特征提取已经完成。但是对于该问题解决方案： !pip install -U git+https://github.com/facebookresearch/fvcore !python -m pip install 'git+https://github.com/facebookresearch/detectron2.git@ffff8ac' 希望对您有帮助！

你好，我想问一下，grid特征提取的代码？因为使用[grid-feats-vqa](https://github.com/facebookresearch/grid-feats-vqa)这个里面的extract_grid_feature.py提取grid特征的维度会有问题，和作者百度云提供的特征不一样

**Comment by hwbhwbgao** [comment]
> 

我没有去专门提取grid特征，不好意思。
