### ISSUE TITLE
怎么评估spice分数

### ISSUE THREAD

**Issue by haijie945** [luo3300612/image-captioning-DLCT#31]
您好，请问需要在模型做哪些设置来评估出spice分数呢？

**Comment by luo3300612** [comment]
运行eval.py的时候加个--spice就行了

**Comment by Baixiaobai201619707** [comment]
@luo3300612 Hello, excuse me. I want to ask you a question，when you train the dlct model, do you encounter the problem that the cache keeps increasing? My cache keeps increasing when I run it and eventually the model gets stuck. Thanks a lot
