### ISSUE TITLE
About features on Baiduyun disk

### ISSUE THREAD

**Issue by john2019-warwick** [luo3300612/image-captioning-DLCT#4]
Hello, could you explain about the features displayed on net disk? is coco_all_align.hdf5 in the zip file? And what are the files end with z01, z02,z03? I have tried to exact the zip file, but fails. 
![feature](https://user-images.githubusercontent.com/57441325/110207455-7b524b00-7e7b-11eb-91c0-e8d1746ddf93.JPG)

**Comment by luo3300612** [comment]
please try to extract on Windows OS

**Comment by john2019-warwick** [comment]
Thanks, I ve already solved this issue, but when it goes to line 138 for training:
https://github.com/luo3300612/image-captioning-DLCT/blob/11cff4c24636a1b54974750889842a1a424c7060/train.py#L138
            reward = torch.from_numpy(reward).to(device).view(detections.shape[0], beam_size)
there is an error: 
![07032021](https://user-images.githubusercontent.com/57441325/110619624-ebb8df00-818f-11eb-8d81-a82acc16d3ee.JPG)
This happens when RL comes in, I think view can't be used because reward before line 138 is a scalar (size1), and it should be enlarged into a vector or matrice with 100 numbers first then it can be changed to 5*20 by view function. Is there any idea for how to fix it according to the context?

**Comment by luo3300612** [comment]
please refer to [issue#5](https://github.com/luo3300612/image-captioning-DLCT/issues/5)
