### ISSUE TITLE
About test performance

### ISSUE THREAD

**Issue by wanboyang** [luo3300612/image-captioning-DLCT#5]
Hello, Thanks for your opening code.
When I train this model from the scratch, training loss is down, but testing performances do not change in training stage

**Comment by wanboyang** [comment]
here are tensorboard log

![Uploading sunlogin_20210307232212.jpg…]()
![Uploading sunlogin_20210307232144.jpg…]()

**Comment by wanboyang** [comment]
![sunlogin_20210307232144](https://user-images.githubusercontent.com/23290289/110245125-f1020800-7f9c-11eb-972e-6a05429969fa.jpg)
![sunlogin_20210307232212](https://user-images.githubusercontent.com/23290289/110245131-f65f5280-7f9c-11eb-8d82-d0c151b0943d.jpg)

**Comment by luo3300612** [comment]
Sorry for getting back to you late. There are some issues in the uploaded evaluation file. So I delete it. You can download the right one [here](https://pan.baidu.com/s/1vE7pzSADe_EYPSGvjPgGtA)(access code ubdc).

**Comment by wanboyang** [comment]
Thank for replying.
