### ISSUE TITLE
parameter error

### ISSUE THREAD

**Issue by lixiangpengcs** [luo3300612/image-captioning-DLCT#6]
Class SelfAtt module includes a MultiHeadAttention module. In its forward function, the self.mhatt receives 6 parameters (q, k, values, relative_geometry_weights, attention_mask, attention_weights). However, there are 5 parameters in MultiHeadAttention's forward function (queries, keys, values,box_relation_embed_matrix, attention_mask, attention_weights). Is this an error? Should it replace MultiHeadAttention with MultiHeadBoxAttention?

**Comment by luo3300612** [comment]
[here](https://github.com/luo3300612/image-captioning-DLCT/blob/main/models/DLCT/encoders.py#L5), we import MultiHeadBoxAttention as MultiHeadAttention
