### ISSUE TITLE
What is the relation between X-101 and X-152 extractors in the code?

### ISSUE THREAD

**Issue by hcl14** [luo3300612/image-captioning-DLCT#9]
Your script `extract_region_feature.py` has weights for X-101 hard-coded. But the file with features has name "region_before_X152.hdf5". Also, there is no information from you which checkpoint to use for extracting grid features. In the paper you mention both X-101 and X-152 as extractors. 

Which extractor checkpoint should I use for grid-feats-vqa: X-101 or X-152? Can I use X-152 for region features as well?

**Comment by luo3300612** [comment]
Both X-101 and X-152 can be used to extract region/grid features. Sorry for the confusing HDF5 filename. It should be "region_before_X101.hdf5"
